In [6]:
%load_ext autoreload
%autoreload 2
import numpy as np
import tensorflow as tf
from features.settings import Baseline_Settings, Triplet_Hinge_Settings, Triplet_Log_Settings
from features.models import ConvModelSmall, ConvModelMedium, ConvModelLarge
from features.models import GCNNModelSmall, GCNNModelMedium, GCNNModelLarge
from classes.models import LinearClassifier0, LinearClassifier1, LinearClassifier2, LinearClassifier3, TwoLayerClassifier
from learn import get_feature_model, get_classifier, train_features, train_classifier, test_model
from datasets import load_mnist_datasets

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


Using TensorFlow backend.


In [7]:
data, samplers, pair_samplers, triplet_samplers = load_mnist_datasets(augment=True)

MNIST loaded in 18 seconds
Fashion MNIST loaded in 36 seconds


In [8]:
tf.reset_default_graph()
f, f_params = get_feature_model(feature_model=ConvModelSmall, settings=Triplet_Hinge_Settings,
                                num_features=10, num_classes=10, data_format=[28, 28, 1],
                                f_lr=0.07, f_reg=0.001, f_scope="f_cms_mnist_10")
fs = tf.train.Saver(tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES, "f_cms_mnist_10"))
d = data['mnist']; s=triplet_samplers['mnist']

In [12]:
c, c_params = get_classifier(classifier=LinearClassifier0, num_features=10, num_classes=10, 
                             c_lr=0.005, c_reg=0.001, c_scope="boosting", f_params=f_params)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    fs.restore(sess, "./models/f_cms_mnist_10.ckpt")
    train_classifier(sess=sess, feature_model=f, classifier=c, data=d, samplers=s, num_steps=5000, 
                     f_params=f_params, c_params=c_params)
    test_model(sess=sess, feature_model=f, classifier=c, samplers=s, data=d, f_params=f_params, c_params=c_params)

INFO:tensorflow:Restoring parameters from ./models/f_cms_mnist_10.ckpt
begin training classifier
	step 0: train loss 2.33491, train error 0.911429
	step 100: train loss 2.2456, train error 0.893333
	step 200: train loss 2.20971, train error 0.683333
	step 300: train loss 2.19599, train error 0.709524
	step 400: train loss 2.17701, train error 0.697143
	step 500: train loss 2.20902, train error 0.72619
	step 600: train loss 2.15796, train error 0.697143
	step 700: train loss 2.16784, train error 0.709048
	step 800: train loss 2.14705, train error 0.699048
	step 900: train loss 2.17079, train error 0.712381
	step 1000: train loss 2.15888, train error 0.708095
	step 1100: train loss 2.17433, train error 0.719048
	step 1200: train loss 2.18846, train error 0.728095
	step 1300: train loss 2.15536, train error 0.70381
	step 1400: train loss 2.18539, train error 0.73381
	step 1500: train loss 2.15881, train error 0.709048
	step 1600: train loss 2.15959, train error 0.710952
	step 1700: train 

NameError: name 'test_error' is not defined

In [14]:
c, c_params = get_classifier(classifier=LinearClassifier1, num_features=10, num_classes=10, 
                             c_lr=0.02, c_reg=0.001, c_scope="boosting", f_params=f_params)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    fs.restore(sess, "./models/f_cms_mnist_10.ckpt")
    train_classifier(sess=sess, feature_model=f, classifier=c, data=d, samplers=s, num_steps=1000, 
                     f_params=f_params, c_params=c_params)
    test_model(sess=sess, feature_model=f, classifier=c, samplers=s, data=d, f_params=f_params, c_params=c_params)

INFO:tensorflow:Restoring parameters from ./models/f_cms_mnist_10.ckpt
begin training features
	step 0: train loss 1.18365, train error 0.424286
	step 10: train loss 1.18504, train error 0.445714
	step 20: train loss 1.182, train error 0.438571
	step 30: train loss 1.18222, train error 0.478571
	step 40: train loss 1.17933, train error 0.44
	step 50: train loss 1.18055, train error 0.458571


KeyboardInterrupt: 

In [ ]:
c, c_params = get_classifier(classifier=LinearClassifier2, num_features=10, num_classes=10, 
                             c_lr=0.02, c_reg=0.001, c_scope="boosting", f_params=f_params)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    fs.restore(sess, "./models/f_cms_mnist_10.ckpt")
    train_classifier(sess=sess, feature_model=f, classifier=c, data=d, samplers=s, num_steps=10000, 
                     f_params=f_params, c_params=c_params)
    test_model(sess=sess, feature_model=f, classifier=c, samplers=s, data=d, f_params=f_params, c_params=c_params)

In [ ]:
c, c_params = get_classifier(classifier=LinearClassifier3, num_features=10, num_classes=10, 
                             c_lr=0.02, c_reg=0.001, c_scope="boosting", f_params=f_params)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    fs.restore(sess, "./models/f_cms_mnist_10.ckpt")
    train_classifier(sess=sess, feature_model=f, classifier=c, data=d, samplers=s, num_steps=10000, 
                     f_params=f_params, c_params=c_params)
    test_model(sess=sess, feature_model=f, classifier=c, samplers=s, data=d, f_params=f_params, c_params=c_params)

# Testing Functionality

In [2]:
sess = tf.InteractiveSession()

In [3]:
data = np.array([[1,2,3,4],[1,7,3,5],[2,4,1,1],[1,3,4,4],[4,4,4,4]])
labels = np.array([0,1,1,2,3])

In [4]:
labels = np.array([0,1,1,2])
a = np.array([[0.8, 0.1, 0.1], [0.1,0.9,0], [0.2,0.8,0],[0,1,0]])
tf.nn.sparse_softmax_cross_entropy_with_logits(labels=labels, logits=a).eval()

array([0.68972664, 0.61836901, 0.69221705, 1.55144471])

In [9]:
b = np.zeros((5, 4))
b[np.arange(5), labels] = 1

In [10]:
print(b)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
labels1 = b[:,1]

In [31]:
for i in range():
    labels = b[:,i]
    print(np.mean(-(labels * np.log(predictions) + (1-labels) * np.log(1-predictions))))
    print(tf.losses.log_loss(labels, predictions).eval())

0.6186249239125281
0.61862475
0.8958837961365061
0.89588344
0.27970577975764666
0.27970564
0.8886102673023313
0.8886099


In [44]:
print(np.mean(-(labels * np.log(predictions) + (1-labels) * np.log(1-predictions))))
print(tf.losses.log_loss(labels, predictions).eval())

[0.61862492 0.8958838  0.27970578 0.88861027]
0.6707059


In [36]:
predictions = np.array([0.3, 0.3, 0.2, 0.7, 0.1]).reshape((5,1))

In [39]:
p = np.repeat(predictions, 4, axis=1)

In [45]:
from keras import losses


Using TensorFlow backend.


In [54]:
B = tf.convert_to_tensor(b.T, np.float32)
P = tf.convert_to_tensor(p.T, np.float32)
print(losses.binary_crossentropy(B, P).eval())

[0.6186249  0.89588386 0.2797058  0.88861024]


In [53]:
p.T

array([[0.3, 0.3, 0.2, 0.7, 0.1],
       [0.3, 0.3, 0.2, 0.7, 0.1],
       [0.3, 0.3, 0.2, 0.7, 0.1],
       [0.3, 0.3, 0.2, 0.7, 0.1]])

In [1]:
import numpy as np

In [ ]:
np.array([[[ 1,  2,  3],
  [ 4,  5,  6]],
 [[ 7,  8,  9],
  [10, 11, 12]]])